# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  my-network:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  monitoring_prometheus:
  monitoring_grafana:

services:
  grafana:
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:6.4.3
    container_name: 'grafana'
    ports:
      - "3000:3000"
    networks:
      - "my-network"
    volumes:
      - monitoring_grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:v2.13.1
    container_name: 'prometheus'
    networks:
      - "my-network"
    ports:
      - "9090:9090"
    volumes:
      - monitoring_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json
  appA:
    # https://hub.docker.com/repository/docker/juliofalbo/dummy-prometheus-target/tags?page=1
    image: juliofalbo/dummy-prometheus-target
    networks:
      - "my-network"
    ports:
      - "8080"
  appB:
    # https://hub.docker.com/repository/docker/juliofalbo/dummy-prometheus-target/tags?page=1
    image: juliofalbo/dummy-prometheus-target
    networks:
      - "my-network"
    ports:
      - "8080"